gathercontent.settings:
  type: mapping
  label: Settings
  mapping:
    gathercontent_username:
      type: string
      label: 'GatherContent username'
    gathercontent_api_key:
      type: string
      label: 'GatherContent API key'
    gathercontent_account:
      type: string
      label: 'GatherContent Account'
    gathercontent_urlkey:
      type: string
      label: 'GatherContent URL key'

gathercontent.import:
  type: mapping
  label: 'Import configuration'
  mapping:
    node_default_status:
      type: integer
      label: 'Default node status'
    node_update_method:
      type: string
      label: 'Content update method'
    node_create_new_revision:
      type: boolean
      label: 'Create new revision'

migrate_plus.source.gathercontent_migration:
  type: migrate_source
  label: 'gathercontent_migration source'
  mapping:
    projectId:
      type: string
    templateId:
      type: string
    tabId:
      type: string

migrate_plus.destination.gc_entity:
  type: migrate_destination
  label: 'gc_entity'
  mapping:
    translations:
      type: boolean
