<?php

/**
 * @file
 * GatherContent Upload UI.
 */

/**
 * Finished callback.
 *
 * @inheritdoc
 */
function gathercontent_upload_finished($success, $results, $operations) {
  $messenger = \Drupal::messenger();

  if ($success) {
    if ($results['success'] > 0) {
      $messenger->addStatus(\Drupal::translation()
        ->formatPlural($results['success'], '1 item was uploaded successfully.', '@count items were uploaded successfully.'));
    }

    if ($results['failed'] > 0) {
      $messenger->addError(\Drupal::translation()
        ->formatPlural($results['failed'], '1 item could not be uploaded. Check errors below.', '@count items could not be uploaded. Check errors below.'));
    }

    if ($results['failed'] == 0 && $results['success'] == 0) {
      $messenger->addStatus(t('Nothing was uploaded.'));
    }

    if (isset($results['messages']) && count($results['messages']) > 0) {
      foreach ($results['messages'] as $message) {
        $messenger->addError($message);
      }
    }
  }
  else {
    $error_operation = reset($operations);

    $messenger->addError(
      t('An error occurred while processing @operation with arguments : @args',
        [
          '@operation' => $error_operation[0],
          '@args' => print_r($error_operation[0], TRUE),
        ]
      )
    );
  }
  return TRUE;
}
