<?php

/**
 * @file
 * Main module file for GatherContent Upload module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\gathercontent\Entity\MappingInterface;

/**
 * Upload batch operation callback.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   Object of entity we want to upload.
 * @param \Drupal\gathercontent\Entity\MappingInterface $mapping
 *   Mapping object.
 * @param int|null $gcId
 *   GatherContent ID.
 * @param array $context
 *   Context of operation.
 */
function gathercontent_upload_process(EntityInterface $entity, MappingInterface $mapping, $gcId = NULL, &$context = []) {
  /** @var \Drupal\gathercontent_upload\Export\Exporter $exporter */
  $exporter = \Drupal::service('gathercontent_upload.exporter');

  if (!isset($context['results']['success'])) {
    $context['results']['success'] = 0;
  }

  if (!isset($context['results']['failed'])) {
    $context['results']['failed'] = 0;
  }

  try {
    $exporter->export($entity, $mapping, $gcId);
    $context['results']['success']++;
  }
  catch (\Exception $e) {
    $context['results']['messages'][] = $e->getMessage();
    $context['results']['failed']++;
  }
}

/**
 * Upload batch operation callback.
 *
 * @param array $mappings
 *   Mapping list keyed by GC ID.
 * @param array $context
 *   Context of operation.
 */
function gathercontent_upload_migrate_update_process(array $mappings, &$context) {
  /** @var \Drupal\gathercontent_upload\Export\Exporter $exporter */
  $exporter = \Drupal::service('gathercontent_upload.exporter');
  try {
    $exporter->updateIdMap($mappings);
  }
  catch (\Exception $e) {
    $context['results']['messages'][] = $e->getMessage();
  }
}
